/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkshopIndexRouteImport } from './routes/_authenticated/workshop/index'
import { Route as AuthenticatedWorkshopSettingsRouteImport } from './routes/_authenticated/workshop/settings'
import { Route as AuthenticatedWorkshopCanvasRouteImport } from './routes/_authenticated/workshop/canvas'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkshopIndexRoute =
  AuthenticatedWorkshopIndexRouteImport.update({
    id: '/workshop/',
    path: '/workshop/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopSettingsRoute =
  AuthenticatedWorkshopSettingsRouteImport.update({
    id: '/workshop/settings',
    path: '/workshop/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopCanvasRoute =
  AuthenticatedWorkshopCanvasRouteImport.update({
    id: '/workshop/canvas',
    path: '/workshop/canvas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/workshop/': typeof AuthenticatedWorkshopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/workshop': typeof AuthenticatedWorkshopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/_authenticated/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/_authenticated/workshop/': typeof AuthenticatedWorkshopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workshop/canvas' | '/workshop/settings' | '/workshop/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workshop/canvas' | '/workshop/settings' | '/workshop'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/workshop/canvas'
    | '/_authenticated/workshop/settings'
    | '/_authenticated/workshop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/': {
      id: '/_authenticated/workshop/'
      path: '/workshop'
      fullPath: '/workshop/'
      preLoaderRoute: typeof AuthenticatedWorkshopIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/settings': {
      id: '/_authenticated/workshop/settings'
      path: '/workshop/settings'
      fullPath: '/workshop/settings'
      preLoaderRoute: typeof AuthenticatedWorkshopSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/canvas': {
      id: '/_authenticated/workshop/canvas'
      path: '/workshop/canvas'
      fullPath: '/workshop/canvas'
      preLoaderRoute: typeof AuthenticatedWorkshopCanvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkshopCanvasRoute: typeof AuthenticatedWorkshopCanvasRoute
  AuthenticatedWorkshopSettingsRoute: typeof AuthenticatedWorkshopSettingsRoute
  AuthenticatedWorkshopIndexRoute: typeof AuthenticatedWorkshopIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkshopCanvasRoute: AuthenticatedWorkshopCanvasRoute,
  AuthenticatedWorkshopSettingsRoute: AuthenticatedWorkshopSettingsRoute,
  AuthenticatedWorkshopIndexRoute: AuthenticatedWorkshopIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
