/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkshopIndexRouteImport } from './routes/_authenticated/workshop/index'
import { Route as AuthenticatedWorkshopSettingsRouteImport } from './routes/_authenticated/workshop/settings'
import { Route as AuthenticatedWorkshopCanvasRouteImport } from './routes/_authenticated/workshop/canvas'
import { Route as AuthenticatedWorkshopToolsPageBuilderRouteImport } from './routes/_authenticated/workshop/tools/page-builder'
import { Route as AuthenticatedWorkshopProjectsProjectIdRouteImport } from './routes/_authenticated/workshop/projects/$projectId'
import { Route as AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRouteImport } from './routes/_authenticated/workshop/tools/page-builder_.html-sandbox'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkshopIndexRoute =
  AuthenticatedWorkshopIndexRouteImport.update({
    id: '/workshop/',
    path: '/workshop/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopSettingsRoute =
  AuthenticatedWorkshopSettingsRouteImport.update({
    id: '/workshop/settings',
    path: '/workshop/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopCanvasRoute =
  AuthenticatedWorkshopCanvasRouteImport.update({
    id: '/workshop/canvas',
    path: '/workshop/canvas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopToolsPageBuilderRoute =
  AuthenticatedWorkshopToolsPageBuilderRouteImport.update({
    id: '/workshop/tools/page-builder',
    path: '/workshop/tools/page-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopProjectsProjectIdRoute =
  AuthenticatedWorkshopProjectsProjectIdRouteImport.update({
    id: '/workshop/projects/$projectId',
    path: '/workshop/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute =
  AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRouteImport.update({
    id: '/workshop/tools/page-builder_/html-sandbox',
    path: '/workshop/tools/page-builder/html-sandbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/workshop/': typeof AuthenticatedWorkshopIndexRoute
  '/workshop/projects/$projectId': typeof AuthenticatedWorkshopProjectsProjectIdRoute
  '/workshop/tools/page-builder': typeof AuthenticatedWorkshopToolsPageBuilderRoute
  '/workshop/tools/page-builder/html-sandbox': typeof AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/workshop': typeof AuthenticatedWorkshopIndexRoute
  '/workshop/projects/$projectId': typeof AuthenticatedWorkshopProjectsProjectIdRoute
  '/workshop/tools/page-builder': typeof AuthenticatedWorkshopToolsPageBuilderRoute
  '/workshop/tools/page-builder/html-sandbox': typeof AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workshop/canvas': typeof AuthenticatedWorkshopCanvasRoute
  '/_authenticated/workshop/settings': typeof AuthenticatedWorkshopSettingsRoute
  '/_authenticated/workshop/': typeof AuthenticatedWorkshopIndexRoute
  '/_authenticated/workshop/projects/$projectId': typeof AuthenticatedWorkshopProjectsProjectIdRoute
  '/_authenticated/workshop/tools/page-builder': typeof AuthenticatedWorkshopToolsPageBuilderRoute
  '/_authenticated/workshop/tools/page-builder_/html-sandbox': typeof AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workshop/canvas'
    | '/workshop/settings'
    | '/workshop/'
    | '/workshop/projects/$projectId'
    | '/workshop/tools/page-builder'
    | '/workshop/tools/page-builder/html-sandbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workshop/canvas'
    | '/workshop/settings'
    | '/workshop'
    | '/workshop/projects/$projectId'
    | '/workshop/tools/page-builder'
    | '/workshop/tools/page-builder/html-sandbox'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/workshop/canvas'
    | '/_authenticated/workshop/settings'
    | '/_authenticated/workshop/'
    | '/_authenticated/workshop/projects/$projectId'
    | '/_authenticated/workshop/tools/page-builder'
    | '/_authenticated/workshop/tools/page-builder_/html-sandbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/': {
      id: '/_authenticated/workshop/'
      path: '/workshop'
      fullPath: '/workshop/'
      preLoaderRoute: typeof AuthenticatedWorkshopIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/settings': {
      id: '/_authenticated/workshop/settings'
      path: '/workshop/settings'
      fullPath: '/workshop/settings'
      preLoaderRoute: typeof AuthenticatedWorkshopSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/canvas': {
      id: '/_authenticated/workshop/canvas'
      path: '/workshop/canvas'
      fullPath: '/workshop/canvas'
      preLoaderRoute: typeof AuthenticatedWorkshopCanvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/tools/page-builder': {
      id: '/_authenticated/workshop/tools/page-builder'
      path: '/workshop/tools/page-builder'
      fullPath: '/workshop/tools/page-builder'
      preLoaderRoute: typeof AuthenticatedWorkshopToolsPageBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/projects/$projectId': {
      id: '/_authenticated/workshop/projects/$projectId'
      path: '/workshop/projects/$projectId'
      fullPath: '/workshop/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedWorkshopProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workshop/tools/page-builder_/html-sandbox': {
      id: '/_authenticated/workshop/tools/page-builder_/html-sandbox'
      path: '/workshop/tools/page-builder/html-sandbox'
      fullPath: '/workshop/tools/page-builder/html-sandbox'
      preLoaderRoute: typeof AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkshopCanvasRoute: typeof AuthenticatedWorkshopCanvasRoute
  AuthenticatedWorkshopSettingsRoute: typeof AuthenticatedWorkshopSettingsRoute
  AuthenticatedWorkshopIndexRoute: typeof AuthenticatedWorkshopIndexRoute
  AuthenticatedWorkshopProjectsProjectIdRoute: typeof AuthenticatedWorkshopProjectsProjectIdRoute
  AuthenticatedWorkshopToolsPageBuilderRoute: typeof AuthenticatedWorkshopToolsPageBuilderRoute
  AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute: typeof AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkshopCanvasRoute: AuthenticatedWorkshopCanvasRoute,
  AuthenticatedWorkshopSettingsRoute: AuthenticatedWorkshopSettingsRoute,
  AuthenticatedWorkshopIndexRoute: AuthenticatedWorkshopIndexRoute,
  AuthenticatedWorkshopProjectsProjectIdRoute:
    AuthenticatedWorkshopProjectsProjectIdRoute,
  AuthenticatedWorkshopToolsPageBuilderRoute:
    AuthenticatedWorkshopToolsPageBuilderRoute,
  AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute:
    AuthenticatedWorkshopToolsPageBuilderHtmlSandboxRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
